# Generated by Django 5.0 on 2024-01-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0003_category_lawyer_experience_lawyer_office_location_and_more'),
    ]

    operations = [
      
        
       
        
        migrations.AddField(
            model_name='lawyer',
            name='description',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
        
        migrations.AddField(
            model_name='lawyer',
            name='working_hours',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='email',
            field=models.EmailField(blank=True, default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='office_location',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='phone',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='phone_number',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
    ]
