# Generated by Django 5.0 on 2024-01-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0004_remove_lawyer_document_remove_lawyer_experience_and_more'),
    ]

    operations = [
        
        
       
        
        migrations.AlterField(
            model_name='lawyer',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='lawyers', to='lawyers.category'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='description',
            field=models.TextField(default='N/A', null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='office_location',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='phone',
            field=models.CharField(default='N/A', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='working_hours',
            field=models.TextField(default='N/A', null=True),
        ),
    ]
