# Generated by Django 5.0 on 2024-01-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0004_remove_lawyer_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='personal_statement',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='practice_areas',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='services',
        ),
        migrations.AddField(
            model_name='lawyer',
            name='description',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='rating',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='working_hours',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='email',
            field=models.EmailField(blank=True, default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='office_location',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='phone',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='phone_number',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
