# Generated by Django 5.0 on 2024-01-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0005_remove_lawyer_experience_remove_lawyer_fax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
