# Generated by Django 5.0 on 2024-01-04 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0005_remove_lawyer_document_remove_lawyer_experience_and_more'),
        ('lawyers', '0006_alter_lawyer_photo'),
    ]

    operations = [
    ]
