# Generated by Django 5.0 on 2024-01-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0007_merge_20240104_0155'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='lawyer',
            name='categories',
            field=models.ManyToManyField(related_name='lawyers', to='lawyers.category'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='name',
            field=models.CharField(default='N/A', max_length=240, verbose_name='Name'),
        ),
    ]
