# Generated by Django 5.0 on 2024-01-04 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0008_remove_lawyer_rating_remove_lawyer_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='website',
        ),
    ]
