# Generated by Django 5.0 on 2024-01-04 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0009_remove_lawyer_rating_remove_lawyer_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='phone_number',
        ),
    ]
