# Generated by Django 5.0 on 2024-01-04 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0010_remove_lawyer_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='description',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='email',
            field=models.EmailField(default='N/A', max_length=254),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='office_location',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='phone',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='photo',
            field=models.ImageField(default='avocat001-230x230_eqCZhNQ.jpg', upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='working_hours',
            field=models.TextField(default='N/A'),
        ),
        migrations.CreateModel(
            name='Appointmnt',
            fields=[
                ('AppointmentID', models.AutoField(primary_key=True, serialize=False, verbose_name='rdvID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('context', models.TextField(default='N/A')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='lawyers.lawyer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='N/A', verbose_name='Comment')),
                ('rating', models.IntegerField(choices=[('3', 3), ('2', 2), ('1', 1), ('5', 5), ('4', 4)], default=0, verbose_name='Stars')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='lawyers.lawyer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
