# Generated by Django 5.0 on 2024-01-04 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0012_alter_review_rating_alter_review_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('2', 2), ('1', 1), ('4', 4), ('5', 5), ('3', 3)], default=0, verbose_name='Stars'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('AppointmentID', models.AutoField(primary_key=True, serialize=False, verbose_name='rdvID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=50, null=True)),
                ('context', models.TextField(default='N/A')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='lawyers.lawyer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Appointmnt',
        ),
    ]
