# Generated by Django 5.0 on 2024-01-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0014_blog_language_remove_appointment_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('2', 2), ('5', 5), ('4', 4), ('1', 1), ('3', 3)], default=0, verbose_name='Stars'),
        ),
    ]
