# Generated by Django 5.0 on 2024-01-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0015_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilavocat',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('4', 4), ('3', 3), ('5', 5), ('1', 1), ('2', 2)], default=0, verbose_name='Stars'),
        ),
    ]
