# Generated by Django 5.0 on 2024-01-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0016_alter_profilavocat_rating_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avocat',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=0, verbose_name='Stars'),
        ),
    ]
