# Generated by Django 5.0 on 2024-01-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0017_alter_avocat_email_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('2', 2), ('1', 1), ('5', 5), ('4', 4), ('3', 3)], default=0, verbose_name='Stars'),
        ),
        migrations.DeleteModel(
            name='Lawyer',
        ),
    ]
