# Generated by Django 5.0 on 2024-01-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0019_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('3', 3), ('4', 4), ('2', 2), ('1', 1), ('5', 5)], default=0, verbose_name='Stars'),
        ),
    ]
