# Generated by Django 5.0 on 2024-01-31 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0022_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilavocat',
            name='avocat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='lawyers.avocat'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('4', 4), ('3', 3), ('1', 1), ('2', 2), ('5', 5)], default=0, verbose_name='Stars'),
        ),
    ]
