# Generated by Django 5.0 on 2024-02-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0023_alter_profilavocat_avocat_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('4', 4), ('1', 1), ('3', 3), ('5', 5), ('2', 2)], default=0, verbose_name='Stars'),
        ),
    ]
